# Generated by Django 6.0.6 on 2026-06-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.category",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
