# Generated by Django 6.0.5 on 2026-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
