# Generated by Django 6.0.5 on 2026-06-03 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("notes", "0004_note_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Якщо вибрати групу, її учасники зможуть переглядати нотатку.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="auth.group",
                verbose_name="Група",
            ),
        ),
    ]
