# Generated by Django 6.0.5 on 2026-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder_telegram_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Нагадування надіслано в Telegram",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="telegram_sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Надіслано в Telegram",
            ),
        ),
    ]
